// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFYPHandler.Data;

#nullable disable

namespace SmartFYPHandler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117162713_AddFYPEntities")]
    partial class AddFYPEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1932),
                            Description = "Web-based applications and websites",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1935),
                            Description = "Mobile applications for iOS and Android",
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1936),
                            Description = "AI and ML projects",
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1937),
                            Description = "Data analysis and visualization projects",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1938),
                            Description = "Desktop software applications",
                            Name = "Desktop Applications"
                        });
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CS",
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1826),
                            Description = "Computer Science and Software Engineering",
                            Name = "Computer Science",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1830)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SE",
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1834),
                            Description = "Software Engineering and Development",
                            Name = "Software Engineering",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1835)
                        },
                        new
                        {
                            Id = 3,
                            Code = "DS",
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1836),
                            Description = "Data Science and Analytics",
                            Name = "Data Science",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1836)
                        },
                        new
                        {
                            Id = 4,
                            Code = "CYB",
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1838),
                            Description = "Cybersecurity and Information Security",
                            Name = "Cybersecurity",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1839)
                        },
                        new
                        {
                            Id = 5,
                            Code = "IT",
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1840),
                            Description = "Information Technology and Systems",
                            Name = "Information Technology",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1840)
                        });
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.DepartmentRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("DepartmentRankings");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.FYPProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Citations")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentRank")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FinalGrade")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("OverallRank")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProjectCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectCategoryId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("FYPProjects");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.IdeaAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputAbstract")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InputTextHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("InputTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OriginalityScore")
                        .HasColumnType("int");

                    b.Property<int>("ResultCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("SimilarityMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IdeaAnalyses");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.IdeaMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdeaAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IndexedDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Snippet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("IdeaAnalysisId");

                    b.HasIndex("IndexedDocumentId");

                    b.ToTable("IdeaMatches");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.IndexedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "Year");

                    b.ToTable("IndexedDocuments");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.ProjectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjectCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1955),
                            Description = "AI and ML related projects",
                            Name = "Machine Learning",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1956)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1959),
                            Description = "Web applications and services",
                            Name = "Web Development",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1959)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1960),
                            Description = "Mobile applications for iOS and Android",
                            Name = "Mobile Development",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1961)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1962),
                            Description = "Internet of Things projects",
                            Name = "IoT",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1962)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1963),
                            Description = "Blockchain and cryptocurrency projects",
                            Name = "Blockchain",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1969)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1970),
                            Description = "Data analysis and visualization",
                            Name = "Data Science",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1971)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1972),
                            Description = "Security and privacy related projects",
                            Name = "Cybersecurity",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 241, DateTimeKind.Utc).AddTicks(1972)
                        });
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.ProjectEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DocumentationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ImplementationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InnovationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PresentationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("TechnicalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectEvaluations");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FYPProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FYPProjectId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 357, DateTimeKind.Utc).AddTicks(4919),
                            Department = "Computer Science",
                            DepartmentId = 1,
                            Email = "admin@smartfyp.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$tPLVYPlKbef.2eJ0qpHO/uLQAp0Y04GkKRZ4uf/9iHB8rG5O5XNoW",
                            Role = 3,
                            StudentId = "",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 27, 13, 357, DateTimeKind.Utc).AddTicks(4923)
                        });
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.UserInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InteractionType")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInteractions");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EngagementLevel")
                        .HasColumnType("int");

                    b.Property<string>("PreferredCategories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCategoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.DepartmentRanking", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.Department", "Department")
                        .WithMany("DepartmentRankings")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartFYPHandler.Models.Entities.FYPProject", "Project")
                        .WithMany("DepartmentRankings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.FYPProject", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.Department", "Department")
                        .WithMany("FYPProjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFYPHandler.Models.Entities.ProjectCategory", null)
                        .WithMany("FYPProjects")
                        .HasForeignKey("ProjectCategoryId");

                    b.HasOne("SmartFYPHandler.Models.Entities.User", "Supervisor")
                        .WithMany("SupervisedFYPProjects")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.IdeaMatch", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.IdeaAnalysis", "IdeaAnalysis")
                        .WithMany("Matches")
                        .HasForeignKey("IdeaAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartFYPHandler.Models.Entities.IndexedDocument", "IndexedDocument")
                        .WithMany()
                        .HasForeignKey("IndexedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdeaAnalysis");

                    b.Navigation("IndexedDocument");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.Project", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFYPHandler.Models.Entities.User", "Supervisor")
                        .WithMany("SupervisedProjects")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.ProjectEvaluation", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.User", "Evaluator")
                        .WithMany("ProjectEvaluations")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFYPHandler.Models.Entities.FYPProject", "Project")
                        .WithMany("ProjectEvaluations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.ProjectMember", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.FYPProject", "FYPProject")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("FYPProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartFYPHandler.Models.Entities.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartFYPHandler.Models.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FYPProject");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.User", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.Department", "DepartmentEntity")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DepartmentEntity");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.UserInteraction", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.FYPProject", "Project")
                        .WithMany("UserInteractions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartFYPHandler.Models.Entities.User", "User")
                        .WithMany("UserInteractions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.UserPreference", b =>
                {
                    b.HasOne("SmartFYPHandler.Models.Entities.ProjectCategory", null)
                        .WithMany("UserPreferences")
                        .HasForeignKey("ProjectCategoryId");

                    b.HasOne("SmartFYPHandler.Models.Entities.User", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("SmartFYPHandler.Models.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.Category", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.Department", b =>
                {
                    b.Navigation("DepartmentRankings");

                    b.Navigation("FYPProjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.FYPProject", b =>
                {
                    b.Navigation("DepartmentRankings");

                    b.Navigation("ProjectEvaluations");

                    b.Navigation("ProjectMembers");

                    b.Navigation("UserInteractions");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.IdeaAnalysis", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.Project", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.ProjectCategory", b =>
                {
                    b.Navigation("FYPProjects");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("SmartFYPHandler.Models.Entities.User", b =>
                {
                    b.Navigation("ProjectEvaluations");

                    b.Navigation("ProjectMemberships");

                    b.Navigation("SupervisedFYPProjects");

                    b.Navigation("SupervisedProjects");

                    b.Navigation("UserInteractions");

                    b.Navigation("UserPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
